[env:esp32-dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM5
monitor_port = COM5
lib_deps = 
    bblanchon/ArduinoJson@^6.21.0
